spring.application.name=easybuy

# ===============================
# DATABASE (PRODUCTION)
# ===============================
spring.datasource.url=postgresql://dpg-d7ifbjjeo5us73dgdo10-a.oregon-postgres.render.com:5432/easybuy_1al0
spring.datasource.username=easybuy_user
spring.datasource.password=E0NjawTWYlR2mPXu8ugKilOYgzKi3yg7
spring.datasource.driver-class-name=org.postgresql.Driver

# ✅ VERY IMPORTANT (stability fix)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

# ===============================
# JPA CONFIG
# ===============================
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
fast2sms.api.key=${FAST2SMS_API_KEY}
# ❌ ये add करो (error avoid करने के लिए)
spring.sql.init.mode=always

# ===============================
# RAZORPAY
# ===============================
razorpay.key=${RAZORPAY_KEY}
razorpay.secret=${RAZORPAY_SECRET}
