spring.application.name=easybuy

# ===============================
# DATABASE CONFIG
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/easydb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Shivay@123

# ===============================
# JPA / HIBERNATE CONFIG
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# SQL INIT CONFIG
# ===============================
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# ===============================
# RAZORPAY TEST CREDENTIALS
# ===============================
razorpay.key=rzp_test_S6Bt3j3ET0UgcM
razorpay.secret=keOUCUPu4U21T65AmgbEXpVz
